name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Remove pycaches
      run: |
        find . -type d -name "__pycache__" -exec rm -r {} +
        find . -type f -name "*.pyc" -exec rm -f {} +

    - name: Run tests
      run: |
        mkdir -p junit
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=.

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml
