name: Run GITHIT Analysis

on: 
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez surveiller

jobs:
  run-githit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Clone the repository
      run: |
        git clone https://github.com/arscg/testCICD.git
        cd testCICD
        # Exécutez votre script ou faites ce qui est nécessaire avec les fichiers clonés
        python script.py  # Remplacez 'script.py' par le script que vous souhaitez exécuter

    - name: Run GITHIT analysis
      run: |
        githit analyze --repository . --output report.txt

    - name: Upload GITHIT report
      uses: actions/upload-artifact@v3
      with:
        name: githit-report
        path: report.txt

