name: Run GITHIT Analysis

on: 
  push:
    branches:
      - main

jobs:
  run-githit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install GITHIT from GitHub
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/arscg/testCICD.git  # Remplacez avec le bon URL

    - name: Run GITHIT analysis
      run: |
        githit analyze --repository . --output report.txt

    - name: Upload GITHIT report
      uses: actions/upload-artifact@v3
      with:
        name: githit-report
        path: report.txt


