name: Run GITHIT Analysis

on: 
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez surveiller

jobs:
  run-githit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'  # Remplacez par la version de Python souhaitée

    - name: Install GITHIT
      run: |
        python -m pip install --upgrade pip
        pip install githit

    - name: Run GITHIT analysis
      run: |
        githit analyze --repository . --output report.txt

    - name: Upload GITHIT report
      uses: actions/upload-artifact@v3
      with:
        name: githit-report
        path: report.txt


